-- MySQL Script generated by MySQL Workbench
-- Fri May 24 14:34:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- HOW TO IMPORT FILE :
-- Open msql server : 
-- mysql -u root -p
-- Create the database :
-- CREATE SCHEMA IF NOT EXISTS `spiritofmanga` DEFAULT CHARACTER SET utf8 ;
-- Exit the database (ctrl+C)
-- Run this command :
-- mysql -u root -p spiritofmanga < databaseCreation.sql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`State` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Public`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Public` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Series` (
  `id` INT NOT NULL,
  `nameSeries` VARCHAR(45) NOT NULL,
  `Type_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Series_Type1_idx` ON `spiritofmanga`.`Series` (`Type_id` ASC);


-- -----------------------------------------------------
-- Table `Mangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Mangas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Series_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `photoCover` VARCHAR(200) NOT NULL,
  `tome` INT NOT NULL,
  `auteur` VARCHAR(45) NOT NULL,
  `editeur` VARCHAR(45) NULL,
  `resume` VARCHAR(500) NOT NULL,
  `State_id` INT NOT NULL,
  `Public_id` INT NOT NULL,
  `prixNeuf` INT NULL,
  `prixHT` INT NOT NULL,
  `TVA` INT NOT NULL,
  `prixSiteTTC` INT NOT NULL,
  `promo` TINYINT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE INDEX `fk_Mangas_Etats1_idx` ON `spiritofmanga`.`Mangas` (`State_id` ASC);

CREATE INDEX `fk_Mangas_Public1_idx` ON `spiritofmanga`.`Mangas` (`Public_id` ASC);

CREATE INDEX `fk_Mangas_Series1_idx` ON `spiritofmanga`.`Mangas` (`Series_id` ASC);


-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `forgetPassword` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone` INT NULL,
  `numRue` INT NOT NULL,
  `rue` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `connaissance` VARCHAR(50) NOT NULL,
  `newsletter` TINYINT NOT NULL,
  `droits` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mangasOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`mangasOrders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  `Mangas_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `disponibilité` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Commandes/Manga_Mangas1_idx` ON `spiritofmanga`.`mangasOrders` (`Mangas_id` ASC);

CREATE INDEX `fk_Commandes/Manga_Users1_idx` ON `spiritofmanga`.`mangasOrders` (`Users_id` ASC);


-- -----------------------------------------------------
-- Table `Packs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Packs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `namePack` VARCHAR(80) NOT NULL,
  `photoPack` VARCHAR(200) NOT NULL,
  `resumePack` VARCHAR(500) NOT NULL,
  `prixTTC` INT NOT NULL,
  `TVA` INT NOT NULL,
  `prixHT` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PacksMangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`PacksMangas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Mangas_id` INT NOT NULL,
  `Packs_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Packs/Mangas_Mangas1_idx` ON `spiritofmanga`.`PacksMangas` (`Mangas_id` ASC);

CREATE INDEX `fk_Packs/Mangas_Packs1_idx` ON `spiritofmanga`.`PacksMangas` (`Packs_id` ASC);


-- -----------------------------------------------------
-- Table `Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `packsOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`packsOrders` (
  `id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `Packs_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `disponibility` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Commandes/Pack_Packs1_idx` ON `spiritofmanga`.`packsOrders` (`Packs_id` ASC);

CREATE INDEX `fk_Commandes/Pack_Users1_idx` ON `spiritofmanga`.`packsOrders` (`Users_id` ASC);


-- -----------------------------------------------------
-- Table `packsAwaiting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`packsAwaiting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `packsOrders_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Pack en attente_Commandes/Pack1_idx` ON `spiritofmanga`.`packsAwaiting` (`packsOrders_id` ASC);


-- -----------------------------------------------------
-- Table `mangasAwaiting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`mangasAwaiting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mangasOrders_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Manga en attente_Commandes/Manga1_idx` ON `spiritofmanga`.`mangasAwaiting` (`mangasOrders_id` ASC);


-- -----------------------------------------------------
-- Table `GenreManga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spiritofmanga`.`GenreManga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Genres_id` INT NOT NULL,
  `Mangas_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_Genre/Manga_Genres1_idx` ON `spiritofmanga`.`GenreManga` (`Genres_id` ASC);

CREATE INDEX `fk_Genre/Manga_Mangas1_idx` ON `spiritofmanga`.`GenreManga` (`Mangas_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
